### ISSUE TITLE
SQL ERROR [ mysqli ]

### ISSUE THREAD

**Issue by xamel** [MarkusWME/phpBB---Smilie-Creator#1]
I get a error if I activate the MOD, please have a look into the error

`SQL ERROR [ mysqli ]

Duplicate entry '14' for key 'PRIMARY' [1062]

SQL

INSERT INTO phpbb_bbcodes (bbcode_id, bbcode_tag, display_on_posting, bbcode_match, bbcode_tpl, first_pass_match, first_pass_replace, second_pass_match, second_pass_replace) VALUES ('14', 'shield', 0, '[shield]{INTTEXT}[/shield]', '<img src=\"./../app.php/pcgf/getsmilieshield?text={INTTEXT}\" alt=\"{L_IMAGE}\"/>', '!\\[shield\\]([\\p{L}\\p{N}\\-+,_. ]+)\\[/shield\\]!iu', '[shield:$uid]${1}[/shield:$uid]', '!\\[shield:$uid\\]([\\p{L}\\p{N}\\-+,_. ]+)\\[/shield:$uid\\]!su', '<img src=\"./../app.php/pcgf/getsmilieshield?text=${1}\" alt=\"{L_IMAGE}\"/>'), (15, 'shield=', 0, '[shield={SIMPLETEXT1},{NUMBER},{SIMPLETEXT2},{SIMPLETEXT3}]{TEXT}[/shield]', '<img src=\"./../app.php/pcgf/getsmilieshield?smilie={SIMPLETEXT1}&shadow={NUMBER}&color={SIMPLETEXT2}&scolor={SIMPLETEXT3}&text={TEXT}\" alt=\"{L_IMAGE}\"/>', '!\\[shield\\=([a-zA-Z0-9-+.,_ ]+),([0-9]+),([a-zA-Z0-9-+.,_ ]+),([a-zA-Z0-9-+.,_ ]+)\\](.*?)\\[/shield\\]!ies', '\'[shield=${1},${2},${3},${4}:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${5}\')).\'[/shield:$uid]\'', '!\\[shield\\=([a-zA-Z0-9-+.,_ ]+),([0-9]+),([a-zA-Z0-9-+.,_ ]+),([a-zA-Z0-9-+.,_ ]+):$uid\\](.*?)\\[/shield:$uid\\]!s', '<img src=\"./../app.php/pcgf/getsmilieshield?smilie=${1}&shadow=${2}&color=${3}&scolor=${4}&text=${5}\" alt=\"{L_IMAGE}\"/>')

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 852
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 650
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 377
CALL: phpbb\db\driver\driver->sql_multi_insert()

FILE: [ROOT]/ext/pcgf/smiliecreator/migrations/release_1_0_0.php
LINE: 112
CALL: phpbb\db\driver\factory->sql_multi_insert()

FILE: (not given by php)
LINE: (not given by php)
CALL: pcgf\smiliecreator\migrations\release_1_0_0->update_bbcode_data()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 591
CALL: call_user_func_array()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 538
CALL: phpbb\db\migrator->run_step()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 361
CALL: phpbb\db\migrator->process_data_step()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 216
CALL: phpbb\db\migrator->try_apply()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 199
CALL: phpbb\db\migrator->update_do()

FILE: [ROOT]/phpbb/extension/base.php
LINE: 80
CALL: phpbb\db\migrator->update()

FILE: [ROOT]/phpbb/extension/manager.php
LINE: 187
CALL: phpbb\extension\base->enable_step()

FILE: [ROOT]/includes/acp/acp_extensions.php
LINE: 177
CALL: phpbb\extension\manager->enable_step()

FILE: [ROOT]/includes/functions_module.php
LINE: 674
CALL: acp_extensions->main()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()`

**Comment by MarkusWME** [comment]
This issue should be fixed now.
It is available in the releases tab or you can download it directly from [this link](https://github.com/MarkusWME/phpBB---Smilie-Creator/releases/download/v1.0.2/smiliecreator-1.0.2.zip).

**Comment by xamel** [comment]
Hey, many thanks ... but the MOD, dont find the path to the pictures
[http://www.maddin1970.alfahosting.org/pictures/dont.find.the.patj.JPG](url)

Another questions, is it possible to add the bubbles?
[http://www.maddin1970.alfahosting.org/pictures/bubbles.JPG](url)



THX and regards
xamel

**Comment by MarkusWME** [comment]
Sorry for my late answer. Had a lot to do the last few days.

The text you can see on the image is the alternative text that appears when the image could not be loaded. So a few questions.
Does the link to the image point to the "app.php/pcgf/getsmilieshield" on your domain? Or do you maybe have an addblocker which blocks the images?
Otherwies if you disable the extension the image also could not be loaded and therefore the alternative text will be shown.

And after the release of another extension I will come back to implement the bubbles as well. So they will be available soon.

**Comment by MarkusWME** [comment]
Bubbles are now implemented. Hope all problems will be solved with the latest release ([v1.1.0](https://github.com/MarkusWME/phpBB---Smilie-Creator/releases/download/v1.1.0/smiliecreator-1.1.0.zip)).

**Comment by MarkusWME** [comment]
I found out what the problem could be. It is described [here](https://www.phpbb.com/community/viewtopic.php?f=466&t=2294581 "Show how to fix the issue"). Hope that solves the problem.
